# Generated by Django 5.2.1 on 2025-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_delete_adminuser_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_type',
            field=models.CharField(choices=[('old_viewer', 'Old Viewer'), ('subscriber', 'Subscriber'), ('fan', 'Fan'), ('lover', 'Lover'), ('cr7_fan', 'CR7 Fan')], default='old_viewer', max_length=20),
        ),
    ]
