# Generated by Django 5.2.1 on 2025-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_membertype_alter_customuser_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
