# Generated by Django 5.2.1 on 2025-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20250524_1218'),
    ]

    operations = [
    ]
