# Generated by Django 5.2.1 on 2025-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_fix_member_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_type',
            field=models.CharField(choices=[('old_viewer', 'Old Viewer'), ('subscriber', 'Subscriber'), ('fan', 'Fan'), ('lover', 'Lover'), ('cr7_fan', 'CR7 Fan'), ('legend', 'Legend')], default='fan', max_length=20),
        ),
        migrations.DeleteModel(
            name='MemberType',
        ),
    ]
