# Generated by Django 5.2.1 on 2025-05-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_customuser_member_type_delete_membertype'),
    ]

    operations = [
    ]
