# Generated by Django 5.2.1 on 2025-05-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
